

server:
  port: 8181

spring:
  application:
    name: carbon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carbon?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 790123
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.yun.carbon.entity
